9name: deploy

# Controls when the workflow will run
on: # 이럴때 실행 해달라
  # Triggers the workflow on push or pull request events but only for the main branch
  push: # push를 할때 
    branches: #어떤것이?
      - master # master의 정보에 push될때마다 실행을 해달라

# 실행
jobs:
  SSH:
    runs-on: ubuntu-latest # 우분투 최신버전으로 컴퓨터를 준비하라 ()

    steps:
      - uses: actions/checkout@v3 # 레파지토리 참고하라
      - name: ssh to ec2 # ec2에 접속하라.
        uses: appleboy/ssh-action@master # 접속 제공 코드
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} # 키페어 필요
          host: ${{ secrets.HOST }} # ip
          username: ${{ secrets.USER }} # 해당 유저 접속 
          port: ${{ secrets.PORT }}
          script: | # 실행 할 코드
            cd BusinessCard  #경로 이동 (실제 존재하는 레파지토리 경로로 이동해야한다.)
            git pull # git pull
            killall -9 java # java 프로세스를 강제로 종료합니다.
            ./gradlew clean build -x test # project build
            cd build/libs # .jar 파일 경로로 이동
            nohup java -jar BusinessCard-0.0.1-SNAPSHOT.jar 1> nohup.err 2> /dev/null & # 백그라운드에서 프로세스가 계속 실행
